name: myco_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  go_router: ^16.0.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  intl: ^0.20.2
  firebase_analytics: ^11.5.0
  firebase_crashlytics: ^4.3.7
  firebase_core: ^3.14.0
  package_info_plus: ^8.3.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  encrypt: ^5.0.3
  connectivity_plus: ^6.1.4
  dartz: ^0.10.1
  url_launcher: ^6.3.1
  pinput: ^5.0.1
  flutter_dotenv: ^5.2.1
  device_preview: ^1.2.0
  flutter_svg: ^2.2.0
  camera: ^0.10.5+9
  badges: ^3.1.2
  dotenv: ^4.2.0
  json_annotation: ^4.9.0
  mobile_scanner:
  table_calendar: ^3.2.0
  flutter_speed_dial:
  fluttertoast: ^8.2.12
  photo_manager: ^3.7.1
  photo_manager_image_provider: ^2.2.0
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  easy_url_launcher: ^0.0.7
  highlight_text: ^1.8.0
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  # Google Map
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  modal_bottom_sheet: ^3.0.0
  bloc: ^9.0.0


dependency_overrides:
  source_gen: 2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.5.1
  retrofit_generator: ^9.2.0
  hive_generator: ^2.0.1
  json_serializable: ^6.9.5

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/svgs/
    - assets/gifs/
    - assets/dashboard/
    - assets/splash/myco_splash.json
    - assets/take_order/
    - assets/sign_in/
    - assets/search_society/
    - assets/ideabox/
    - assets/payslip/
    - assets/visit/
    - assets/media_picker/
    - assets/employees/
    - assets/stepper/
    - assets/lost_and_found/
    - assets/visit_svgs/
    - assets/svgs/visit/
    - assets/add_expense/
    - assets/dashboard/svgs/
#    - assets/face_detection/
    - assets/svgs/visit/
    - assets/dashboard/svgs/
#    - assets/face_detection/
#    - assets/dashboard/svgs/
    - assets/assets/
    - assets/svgs/take_order/
    - assets/animations/
    - assets/stepper/
    - assets/dashboard/svgs/
    - assets/assets/
    - assets/svgs/take_order/
    - assets/animations/
    - assets/stepper/
    - assets/assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy-Thin
      fonts:
        - asset: assets/fonts/Gilroy-Thin.ttf
    - family: Gilroy-UltraLight
      fonts:
        - asset: assets/fonts/Gilroy-UltraLight.ttf
    - family: Gilroy-Light
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
    - family: Gilroy-Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
    - family: Gilroy-Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: Gilroy-ExtraBold
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
    - family: Gilroy-Heavy
      fonts:
        - asset: assets/fonts/Gilroy-Heavy.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package